routes/web.php
<?php

Route::get('/', 'VendasController@grafanos')
->name('vendas.grafanos')
->middleware('auth');

Auth::routes();

Route::group(['prefix'=>'admin', 'middleware' => 'auth'], function () {
    
    Route::resource('empresas', 'EmpresasController');
    Route::resource('estoques', 'EstoquesController');
    Route::resource('instrutores', 'InstrutoresController');
    Route::resource('compras', 'ComprasController');
    Route::resource('tiposInsumos', 'TiposInsumosController');
    Route::resource('insumos', 'InsumosController');
    Route::resource('visitas', 'VisitasController');
    Route::resource('lavouras', 'LavourasController');
    Route::resource('plantacoes', 'PlantacoesController');
    Route::resource('vendas', 'VendasController');
    Route::resource('classes', 'ClassesController');
    Route::resource('producoes', 'ProducoesController');
    Route::resource('marcas', 'MarcasController');
    Route::resource('estimativas', 'EstimativaController');

    //relatorios escolha venda
    Route::get('relEscolha', 'VendasController@relEscolha')
    ->name('relEscolha');
    Route::post('relItensVendas', 'VendasController@relItensVendas')
    ->name('relItensVendas');

    //relatorios escolha anos
    Route::get('relEscolhaAno', 'VendasController@relEscolhaAno')
    ->name('relEscolhaAno');
    Route::post('relAnos', 'VendasController@relAnos')
    ->name('relAnos');

    //relatorios escolha compra
    Route::get('relEscolha2', 'ComprasController@relEscolha')
    ->name('relEscolha2');
    Route::post('relItensComprados', 'ComprasController@relItensCompras')
    ->name('relItensComprados');

    //relatorios escolha insumo
    Route::get('relEscolha3', 'InsumosController@relEscolha')
    ->name('relEscolha3');
    Route::post('relInsumos', 'InsumosController@relInsumos')
    ->name('relInsumos');

    //historico de compras
    Route::get('historicoCompras', 'ComprasController@historico')
    ->name('historicoCompras');
    // filtro do historico
    Route::post('pesquisaHistoricoCompras', 'ComprasController@pesquisa')
    ->name('pesquisaHistoricoCompras');

    //historico de vendas
    Route::get('historicoVendas', 'VendasController@historico')
    ->name('historicoVendas');
    // filtro do historico
    Route::post('pesquisaHistoricoVendas', 'VendasController@pesquisa')
    ->name('pesquisaHistoricoVendas');

    //vendas de fumo
    Route::get('indexFumoVendido/{id}', 'VendasController@index2')
    ->name('indexFumoVendido');

    Route::post('createFumoVendido/{id}', 'VendasController@create2')
    ->name('createFumoVendido');

    Route::delete('destroyFumoVendido/{id}', 'VendasController@destroy2')
    ->name('destroyFumoVendido');


    //itens compras
    Route::get('indexItensComprados/{id}', 'ComprasController@index2')
    ->name('indexItensComprados');

    Route::post('createItensComprados/{id}', 'ComprasController@create2')
    ->name('createItensComprados');

    Route::delete('destroytensComprados/{id}', 'ComprasController@destroy2')
    ->name('destroytensComprados');


    //baixas de insumos
    Route::get('indexBaixasInsumos', 'InsumosController@index2')
    ->name('indexBaixasInsumos');
    
    Route::put('createBaixasInsumos/{id}', 'InsumosController@create2')
    ->name('createBaixasInsumos');
    
    Route::delete('destroyBaixasInsumos/{id}', 'InsumosController@destroy2')
    ->name('destroyBaixasInsumos');


    //graficos vendas
    Route::get('vendasempgraf', 'VendasController@grafemp')
    ->name('vendas.grafemp');

    //graficos compras
    Route::get('comprasempgraf', 'ComprasController@grafemp')
    ->name('compras.grafemp');

    //graficos marcas por insumos
    Route::get('marcasInsumosgraf', 'InsumosController@grafInsMar')
    ->name('compras.grafInsMar');

});

Auth::routes();

resources/views/baixarInsumos.blade.php
@extends('adminlte::page')

@section('title', 'Baixa de Insumos')

@section('content')

<div class="container-fluid">
  @section('content_header')
          <h1>Baixar Insumos<h1>
  @endsection

   
    @foreach($insumos as $i)   
    <form method="POST" action="{{ route('createBaixasInsumos', $i->id) }}" enctype="multipart/form-data">
    {!! method_field('put') !!}
    @endforeach
      {{ csrf_field() }}

    <div class="row" style="margin-left: 300px;">
        <div class="col-sm-4">
            <div class="form-group">
              <label for="insumos_id">Insumo</label>
              <select id="insumos_id" name="insumos_id" class="form-control" onChange="setQuant()">
                    @foreach($insumos as $i)
                    <option value="{{$i->id}}" 
                        {{ ((isset($reg) and $reg->insumos_id == $i->id) or 
                                 old('insumos_id') == $i->id) ? "selected" : "" }}>
                              {{$i->nome}}</option>
                              @endforeach
                            </select>  
            </div>
          </div>
      <div class="col-sm-2">
        <div class="form-group">
          <label for="quant">Baixar Estoque</label>
          <input type="number" onkeypress="return event.charCode >= 1000" min="0" max="0" id="quant" name="quant" 
           class="form-control">
        </div>
      </div>
    </div>
    <div class="row" style="margin-left: 300px;">
      <div class="col-sm-4">
        <div class="form-group">
          <label for="motivo">Motivo</label>
          <input type="text" id="motivo" name="motivo" class="form-control">             
        </div>
      </div>
    </div>

    <div style="margin-left: 540px;">
    <input type="submit" value="Enviar" class="btn btn-success">
    <input type="reset" value="Limpar" class="btn btn-warning">
</div>

    </form>
  </div>

<br>

<table class="table table-hover" id="tabela">
  <tr>
    <th>Insumo</th>
    <th>Motivo</th>
    <th>Quantidade</th>
    <th>Data</th>
    <th>Ações</th>
  </tr>
  
  @forelse ($baixarInsumos as $bi)
  <tr id="tabelaResultado">
    <td> {{$bi->insumos->nome}} </td>
    <td> {{$bi->motivo}} </td>
    <td> {{$bi->quant}} </td>
    <td> {{date_format($bi->created_at, 'd/m/Y')}} </td>
    <td> 
        <form style="display: inline-block"
              method="post"
              action="{{route('destroyBaixasInsumos', $bi->id)}}"
              onsubmit="return confirm('Confirma Exclusão?')">
               {{method_field('delete')}}
               {{csrf_field()}}
              <button type="submit" title="Excluir"
                      class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
        </form>            
    </td>
    
    @empty
    <tr id="vazio"><td colspan=8> Não há insumos baixados</td></tr>
    
    @endforelse
{{ $baixarInsumos->links() }}
    
</table>  

<script>
//pega o elemento insumos_id
  var inputBaixarInsumos = document.getElementById("insumos_id");
  //pega a quant
  var inputQuant = document.getElementById("quant");

// cria o vetor
  var quantsInsumos = [];

<?php
// cria o indice 0
  $indiceVetor = 0;

  foreach ($insumos as $insumo) {
    // pega a quant do vetor
    echo "\nquantsInsumos[".$indiceVetor."] = ".$insumo->quant.";";
    $indiceVetor++;
  }
?>

// seta a quant inicial
setQuant();

function setQuant() {
  var pos = inputBaixarInsumos.selectedIndex;
  inputQuant.max = quantsInsumos[pos];
  inputQuant.value = quantsInsumos[pos];
}

 </script>

@endsection

resources/views/compras.blade.php
@extends('adminlte::page')

@section('title', 'Listagem de Compras')

@section('content')

<div class="container-fluid">
    @section('content_header')
    <h1>Cadastro de Compras</h1>
    @endsection

    @if ($acao==1)
      <form method="POST" action="{{ route('compras.store') }}" enctype="multipart/form-data">
    @else ($acao==2)
      <form method="POST" action="{{route('compras.update', $reg->id)}}" enctype="multipart/form-data">
      {!! method_field('put') !!}
    @endif          
    {{ csrf_field() }}
    
    
    <div class="row" style="margin-left: 415px;">
        <div class="col-sm-4">
          <div class="form-group">
             
            <label for="empresas_id">Empresa</label>
            <select id="empresas_id" name="empresas_id" class="form-control">
              @foreach($empresas as $emp)
                <option value="{{$emp->id}}" 
                        {{ ((isset($reg) and $reg->empresas_id == $emp->id) or 
                           old('empresas_id') == $emp->id) ? "selected" : "" }}>
                        {{$emp->nome}}</option>
              @endforeach
            </select>  
          </div>
        </div>
      </div>
     
        <div style="margin-left: 580px;">
            <input type="submit" value="Enviar" class="btn btn-success">
        </div>
      </form>
  </div>

  <br>

  <table class="table table-hover" id="tabela">
    <tr>
      <th>Total R$</th>
      <th>Comprado da Empresa</th>
      <th>Data</th>
      <th>Ações</th>
    </tr>
    @forelse ($compras as $c)
    <tr id="tabelaResultado">
        <td> {{number_format($c->total, 2, ',', '.')}} </td>
        <td> {{$c->empresas->nome}} </td>        
        <td> {{date_format($c->created_at, 'd/m/Y')}} </td>
        
        <td> 
                     <a href="{{route('indexItensComprados', $c->id)}}" 
                class="btn btn-success btn-sm" title="Adicionar Insumos"
                role="button"><i class="fas fa-plus-circle"></i></a>
            <form style="display: inline-block"
                  method="post"
                  action="{{route('compras.destroy', $c->id)}}"
                  onsubmit="return confirm('Confirma Exclusão?')">
                   {{method_field('delete')}}
                   {{csrf_field()}}
                  <button type="submit" title="Excluir"
                          class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
            </form>
        </td>
        @if ($loop->iteration == $loop->count)
             <tr><td colspan=8>Total das Compras Feitas R$: 
                               {{number_format($soma, 2, ',', '.')}}
                              ---- Nº de Compras: {{$numCompras}}                              
                              </td></tr>                    
        @endif        
    @empty
      <tr id="vazio"><td colspan=8> Não há compras cadastrados </td></tr>
    @endforelse

</table>  
{{ $compras->links() }}

@stop

resources/views/compras_graf.blade.php
@extends('adminlte::page')

@section('title', 'Gráfico de Compras por Empresas')

@section('content_header')
    <h1>Gráfico de Compras por Empresas
    <a href="{{route('compras.index')}}" class="btn btn-primary pull-right" title="Ver Vendas"
       role="button"><i class="fas fa-eye"></i></a>
    </h1>
@stop


@section('content')

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Empresas', 'Nº de Compras'],
@foreach ($compras as $compra) 
{!! "['$compra->empresas', $compra->num]," !!}
@endforeach  

        ]);

        var options = {
          title: 'Nº de Compras por Empresa',
          is3D: true,
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
        chart.draw(data, options);
      }
    </script>

    <div id="piechart_3d" style=" height: 500px;"></div>

  @endsection

resources/views/historicosCompras.blade.php
@extends('adminlte::page')

@section('title', 'Historico de Compras')

@section('content')

    @section('content_header')
    <h1>Histórico de Compras</h1>
    @endsection
    
    <form action="{{route('pesquisaHistoricoCompras')}}" method="POST" class="form form-inline pull-right">
        {{ csrf_field() }}
        <input type="date" name="date" class="form-control"">
        <input type="text" name="total" id="total" class="form-control" placeholder="Total">
        <select id="empresas_id" name="empresas_id" class="form-control">
            <option value="">--- Selecione a empresa ---</option>
            @foreach($empresas as $emp)
              <option value="{{$emp->id}}" 
                      {{ ((isset($reg) and $reg->empresas_id == $emp->id) or 
                         old('empresas_id') == $emp->id) ? "selected" : "" }}>
                      {{$emp->nome}}  </option>
            @endforeach
          </select>  
        <button type="submit" class="btn btn-primary" title="Pesquisar"><i class="fas fa-search"></i></button>
        <a href="{{ route('historicoCompras') }}"  class="btn btn-warning" role="button" title="Todos"><i class="fas fa-list"></i></a>
    </form>


  <table class="table table-hover" id="tabela">
    <tr>
      <th>Total R$</th>
      <th>Comprado da Empresa</th>
      <th>Data</th>
    </tr>
    @forelse ($compras as $c)
    <tr id="tabelaResultado">
        <td> {{number_format($c->total, 2, ',', '.')}} </td>
        <td> {{$c->empresas->nome}} </td>        
        <td> {{date_format($c->created_at, 'd/m/Y')}} </td>
              
    @empty
      <tr id="vazio"><td colspan=8> Não há resultados de pesquisa ou compras feitas</td></tr>
    @endforelse

</table>  
{{ $compras->links() }}

  
@section('js')
  <script src="https://code.jquery.com/jquery-latest.min.js"></script>
  <script src="/js/jquery.mask.min.js"></script>
<script>
  $(document).ready(function() {
    $('#total').mask('#.###.##0,00', {reverse: true});
  });
</script> 
@endsection
@stop

resources/views/marcasInsumos_graf.blade.php
@extends('adminlte::page')

@section('title', 'Marcas por Insumos')

@section('content_header')
    <h1>Marcas por Insumos
    {{-- <a href="{{route('vendas.index')}}" class="btn btn-primary pull-right" title="Ver Vendas"
       role="button"><i class="fas fa-eye"></i></a> --}}
    </h1>
@stop


@section('content')

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Marcas', 'Nº de Insumos'],
@foreach ($insumos as $insumo) 
{!! "['$insumo->marcas', $insumo->num]," !!}
@endforeach          
        ]);

        var options = {
          title: 'Nº de Insumos por Marcas',
          is3D: true,
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
        chart.draw(data, options);
      }
    </script>

    <div id="piechart_3d" style=" height: 500px;"></div>

@endsection

resources/views/plantacoes.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Plantações')

@section('content')

<div class="container-fluid">
    @section('content_header')
    <h1>Cadastro de Plantações</h1>
@endsection

    @if ($acao==1)
      <form method="POST" action="{{ route('plantacoes.store') }}" enctype="multipart/form-data">
    @else ($acao==2)
      <form method="POST" action="{{ route('plantacoes.update', $reg->id)}}" enctype="multipart/form-data">
      {!! method_field('put') !!}
    @endif          
    {{ csrf_field() }}

    
    <div class="row" style="margin-left: 250px;">
      <div class="col-sm-4">
        <div class="form-group">
          <label for="lavouras_id">Qual Lavoura?</label>
          <select id="lavouras_id" name="lavouras_id" class="form-control">
            @foreach($lavouras as $l)
              <option value="{{$l->id}}" 
                      {{ ((isset($reg) and $reg->lavouras_id == $l->id) or 
                         old('lavouras_id') == $l->id) ? "selected" : "" }}>
                      {{$l->descricao}}</option>
            @endforeach
          </select>  
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <label for="quant">Quantidade Plantada</label>
          <input type="text" id="quant" name="quant"
                 value="{{$reg->quant or old('quant')}}"
                 class="form-control">
            <strong>{{ $errors->first('quant') }}</strong>                 
        </div>
      </div>
    </div>
    <div class="row" style="margin-left: 250px;">

      <div class="col-sm-4">
        <div class="form-group">
          <label for="observacao">Observação</label>
          <textarea name="observacao" id="observacao" cols="63,9" rows="5"></textarea> 
        </div>
      </div>
    </div>

    

    <div class="col-sm-4">   
      <input type="hidden" id="users_id" name="users_id"
      value="{{auth()->user()->id}}" class="form-control">
    </div>

    <div style="margin-left: 650px;">
    <input type="submit" value="Enviar" class="btn btn-success">
    <input type="reset" value="Limpar" class="btn btn-warning">
</div>
    </form>
  </div>

  <br>
  @if (session('status'))
  <div class="alert-danger" style="text-align: center">
        {{ session('status') }}
      </div>  
      <script>
          setTimeout(function(){ 
            var msg = document.getElementsByClassName("alert-danger");
              while(msg.length > 0){
                  msg[0].parentNode.removeChild(msg[0]);
              }
          }, 3000);
      </script>
   @endif
   
<table class="table table-hover" id="tabela">
    <tr>
      <th>Quantidade Plantada (Mil)</th>
      <th>Observação</th>
      <th>Lavoura</th>
      <th>Data do Plantio</th>
      <th>Ações</th>
    </tr>
    @forelse ($plantacoes as $p)
    <tr id="tabelaResultado">
        <td> {{number_format($p->quant, 2, ',', '.')}} </td> 
        <td> {{$p->observacao}} </td>    
        <td> {{$p->lavouras->descricao}} </td>    
        <td> {{date_format($p->created_at, 'd/m/Y')}} </td>
        
        <td> 
            <a href="{{route('plantacoes.edit', $p->id)}}" 
                class="btn btn-warning btn-sm" title="Alterar"
                role="button"><i class="fa fa-edit"></i></a>
            <form style="display: inline-block"
                  method="post"
                  action="{{route('plantacoes.destroy', $p->id)}}"
                  onsubmit="return confirm('Confirma Exclusão?')">
                   {{method_field('delete')}}
                   {{csrf_field()}}
                  <button type="submit" title="Excluir"
                          class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
            </form>
        </td>     
        @if ($loop->iteration == $loop->count)
        <tr><td colspan=8>Total plantado: 
                          {{number_format($soma, 2, ',', '.')}}                            
                         </td></tr>
                       
   @endif   
    @empty
      <tr id="vazio"><td colspan=8> Não há plantações cadastradas </td></tr>
    @endforelse

</table>  

{{ $plantacoes->links() }}
@stop

@section('js')
  <script src="https://code.jquery.com/jquery-latest.min.js"></script>
  <script src="/js/jquery.mask.min.js"></script>

  <script>
    $(document).ready(function() {
      $('#quant').mask('#.###.##0,00', {reverse: true});
    });
  </script> 
  @endsection

resources/views/relInsumo.blade.php
@section('title', 'Relatórios de Insumos')


<h1 style="color: green">Tabaco Admin</h1>
<title>Relatório de Insumos</title>
<h2>Relatório de Insumos</h2>
<link rel="stylesheet" type="text/css" href="vendor/adminlte/css/estilo.css">


<table border="1" widht=100% class="table1">
  <tr class="tabTop">
    <th>Nome</th>
    <th>Marca</th>
    <th>Tipo</th>
    <th>Quantidade</th>
  </tr>    

@foreach($insumo as $i)
<tr>
    <td>{{$i->nome }} </td>
    <td>{{$i->marcas->nome }} </td>
    <td>{{$i->tiposInsumos->nome}}</td>
    <td>{{$i->quant}}</td>   
  </tr>    
@endforeach  
</table>

resources/views/tiposInsumos.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Tipos de Insumos')

@section('content')

<div class="container-fluid">
  @section('content_header')
  <h2>Cadastro de Tipos de Insumos</h2>
@endsection

  @if ($acao==1)
    <form method="POST" action="{{ route('tiposInsumos.store') }}" enctype="multipart/form-data">
  @else ($acao==2)
    <form method="POST" action="{{ route('tiposInsumos.update', $reg->id)}}" enctype="multipart/form-data">
    {!! method_field('put') !!}
  @endif          
  {{ csrf_field() }}

  
  <div class="row" style="margin-left: 375px;">
    <div class="col-sm-5">
      <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" id="nome" name="nome" autofocus
               value="{{$reg->nome or old('nome')}}"
               class="form-control">
               <strong>{{ $errors->first('nome') }}</strong>

      </div>
    </div>
  </div>
  

  <div style="margin-left: 515px;">
  <input type="submit" value="Enviar" class="btn btn-success">
  <input type="reset" value="Limpar" class="btn btn-warning">
</div>

  </form>
</div>

<br>
@if (session('status'))
<div class="alert-danger" style="text-align: center">
      {{ session('status') }}
    </div>  
    <script>
        setTimeout(function(){ 
            var msg = document.getElementsByClassName("alert-danger");
            while(msg.length > 0){
                msg[0].parentNode.removeChild(msg[0]);
            }
        }, 3000);
    </script>
@endif

<table class="table table-hover" id="tabela">
  <tr>
    <th> Tipo </th>
    <th> Ações </th>
  </tr>  
@forelse($tiposInsumos as $ti)
  <tr id="tabelaResultado">
    <td> {{$ti->nome}} </td>  
    <td> 
        <a href="{{route('tiposInsumos.edit', $ti->id)}}" 
            class="btn btn-warning btn-sm" title="Alterar"
            role="button"><i class="far fa-edit"></i></a>
        <form style="display: inline-block"
              method="post"
              action="{{route('tiposInsumos.destroy', $ti->id)}}"
              onsubmit="return confirm('Confirma Exclusão?')">
               {{method_field('delete')}}
               {{csrf_field()}}
              <button type="submit" title="Excluir"
                      class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
        </form>            
    </td>
  </tr>

@empty
  <tr id="vazio"><td colspan=8> Não há tipos de insumos cadastrados</td></tr>
@endforelse
</table>
{{ $tiposInsumos->links() }}
@endsection

resources/views/vendas_graf.blade.php
@extends('adminlte::page')

@section('title', 'Gráfico de Vendas por Empresas')

@section('content_header')
    <h1>Gráfico de Vendas por Empresas
    <a href="{{route('vendas.index')}}" class="btn btn-primary pull-right" title="Ver Vendas"
       role="button"><i class="fas fa-eye"></i></a>
    </h1>
@stop


@section('content')

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Empresas', 'Nº de Vendas'],
@foreach ($vendas as $venda) 
{!! "['$venda->empresas', $venda->num]," !!}
@endforeach          
        ]);

        var options = {
          title: 'Nº de Vendas por Empresa',
          is3D: true,
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
        chart.draw(data, options);
      }
    </script>

    <div id="piechart_3d" style=" height: 500px;"></div>

@endsection

resources/views/vendasanos_graf.blade.php
@extends('adminlte::page')

@section('title', 'Gráfico de Vendas por Anos')

@section('content_header')
    <h1>Gráfico de Vendas por Ano
    <a href="{{route('vendas.index')}}" class="btn btn-primary pull-right" title="Ver Vendas"
       role="button"><i class="fas fa-eye"></i></a>
    </h1>
@stop


@section('content')

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Ano', 'Nº de Vendas'],
@foreach ($vendas as $venda) 
{!! "['$venda->anos', $venda->num]," !!}
@endforeach          
        ]);

        var options = {
          title: 'Nº de Vendas por Ano',
          is3D: true,
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
        chart.draw(data, options);
      }
    </script>

    <div id="piechart_3d" style=" height: 500px;"></div>

@endsection

resources/views/visitas.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Instrutores')

@section('content')

<div class="container-fluid">
    @section('content_header')
    <h1>Cadastro de Visitas</h1>
@endsection

    @if ($acao==1)
      <form method="POST" action="{{ route('visitas.store') }}" enctype="multipart/form-data">
    @elseif ($acao==2)
      <form method="POST" action="{{route('visitas.update', $reg->id)}}" enctype="multipart/form-data">
      {!! method_field('put') !!}
    @endif          
    {{ csrf_field() }}

    <div class="row" style="margin-left: 250px;">
      <div class="col-sm-4">
        <div class="form-group">
          <label for="motivo">Motivo</label>
          <input type="text" id="motivo" name="motivo" autofocus
                 value="{{$reg->motivo or old('motivo')}}"
                 class="form-control">
                 <strong>{{ $errors->first('motivo') }}</strong>                 
        </div>
      </div>

      <div class="col-sm-4">
        <div class="form-group">
          <label for="instrutors_id">Instrutor</label>
          <select id="instrutors_id" name="instrutors_id" class="form-control">
            @foreach($instrutores as $ins)
              <option value="{{$ins->id}}" 
                      {{ ((isset($reg) and $reg->instrutors_id == $ins->id) or 
                         old('instrutors_id') == $ins->id) ? "selected" : "" }}>
                      {{$ins->nome}}</option>
            @endforeach
          </select>  
        </div>
      </div>
    </div>              

    <div class="row" style="margin-left: 250px;">
        <div class="col-sm-4">
          <div class="form-group">
            <label for="observacao">Observação</label>
            <textarea inputmode="latin-name" name="observacao" id="observacao" cols="45" rows="5" 
            value="{{$reg->observacao or old('observacao')}}"></textarea> 
            <strong>{{ $errors->first('observacao') }}</strong>                 
          </div>
        </div>
     </div>
     
     <div style="margin-left: 655px;">
        <input type="submit" value="Enviar" class="btn btn-success">
        <input type="reset" value="Limpar" class="btn btn-warning">
      </div>
      
    </form>
  </div>
  
  <br>

<table class="table table-hover" id="tabela">
    <tr>
        <th>Instrutor</th>
      <th>Motivo</th>
      <th>Observação</th>
      <th>Data</th>
      <th>Ações</th>
    </tr>
      
    @forelse ($visitas as $v)
      <tr id="tabelaResultado">
          <td> {{$v->instrutors->nome}} </td>
        <td> {{$v->motivo}} </td>
        <td> {{$v->observacao}} </td>
        <td> {{date_format($v->created_at, 'd/m/Y')}} </td>
        <td> 
            <a href="{{route('visitas.edit', $v->id)}}" 
                class="btn btn-warning btn-sm" title="Alterar"
                role="button"><i class="fa fa-edit"></i></a>
            <form style="display: inline-block"
                  method="post"
                  action="{{route('visitas.destroy', $v->id)}}"
                  onsubmit="return confirm('Confirma Exclusão?')">
                   {{method_field('delete')}}
                   {{csrf_field()}}
                  <button type="submit" title="Excluir"
                          class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
            </form>
        </td>
            
    @empty
      <tr id="vazio"><td colspan=8> Não há visitas cadastradas </td></tr>
    @endforelse

</table>  
{{ $visitas->links() }}

@stop